# Generated by Django 5.2.5 on 2025-11-30 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movieviewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_view_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity'], name='movies_movi_popular_114287_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_average'], name='movies_movi_vote_av_ca6eee_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'),
        ),
        migrations.AddIndex(
            model_name='moviestats',
            index=models.Index(fields=['avg_rating'], name='movies_movi_avg_rat_ad12ed_idx'),
        ),
        migrations.AddIndex(
            model_name='moviestats',
            index=models.Index(fields=['reviews_count'], name='movies_movi_reviews_9c2646_idx'),
        ),
        migrations.AddIndex(
            model_name='moviestats',
            index=models.Index(fields=['favorites_count'], name='movies_movi_favorit_cab6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='moviestats',
            index=models.Index(fields=['watch_count'], name='movies_movi_watch_c_dcb626_idx'),
        ),
        migrations.AddIndex(
            model_name='moviestats',
            index=models.Index(fields=['trending_score'], name='movies_movi_trendin_9199a8_idx'),
        ),
        migrations.AddIndex(
            model_name='movieviewlog',
            index=models.Index(fields=['user'], name='movie_view__user_id_d915f9_idx'),
        ),
        migrations.AddIndex(
            model_name='movieviewlog',
            index=models.Index(fields=['movie'], name='movie_view__movie_i_2d2ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='movieviewlog',
            index=models.Index(fields=['timestamp'], name='movie_view__timesta_347a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['rank'], name='movies_tren_rank_8d6d39_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['score'], name='movies_tren_score_d677fe_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['fetched_at'], name='movies_tren_fetched_ca94ca_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['movie'], name='movies_tren_movie_i_246846_idx'),
        ),
        migrations.AddConstraint(
            model_name='trendingmovie',
            constraint=models.UniqueConstraint(fields=('movie', 'fetched_at'), name='unique_trending_movie_per_fetch'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user'], name='watchlist_user_id_c64328_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['movie'], name='watchlist_movie_i_58e72a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['watched_at'], name='watchlist_watched_214202_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_watchlist'),
        ),
    ]
